name: CI/CD 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Optional image tag to deploy to production (sha or semantic tag). If empty, uses the last built sha.'
        required: false
        default: ''

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-and-push:
    name: Build & Push Image
    runs-on: ubuntu-latest
    outputs:
      image-ref: ${{ steps.set-output.outputs.image_ref }}
      image-digest: ${{ steps.build.outputs.digest }}
      image-tag: ${{ steps.set-output.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-platform support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::898896902478:role/GitHubOIDCRole
          aws-region: us-west-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-west-1 \
            | docker login --username AWS --password-stdin public.ecr.aws/w8a6s2p8/app

      # - name: Run unit tests
      #   run: |
      #     echo "Running unit tests..."
      #     pytest -q || true

      - name: Build and push (multi-platform)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            public.ecr.aws/w8a6s2p8/app:latest
            public.ecr.aws/w8a6s2p8/app:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Set output (image ref & tag)
        id: set-output
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          # Use full SHA for image_tag output to be unambiguous
          IMAGE_TAG_FULL=${{ github.sha }}
          IMAGE_REF="public.ecr.aws/w8a6s2p8/app:${IMAGE_TAG_FULL}"
          echo "image_ref=${IMAGE_REF}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG_FULL}" >> $GITHUB_OUTPUT
          echo "Built and pushed ${IMAGE_REF}"
  
  deploy-staging:
    name: Deploy to Staging (automatic)
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::898896902478:role/GitHubOIDCRole
          aws-region: us-west-1

      - name: Update kubeconfig (staging)
        run: |
          aws eks update-kubeconfig --region us-west-1 --name voting-cluster 

      - name: Verify kubectl
        run: kubectl get nodes

      - name: Helm deploy to staging
        env:
          IMAGE_TAG: ${{ needs.build-and-push.outputs.image-tag }}
        run: |
          Helm upgrade --install app ./Helm \
            --namespace voting-app --create-namespace \
            --set image.repository=public.ecr.aws/w8a6s2p8/app \
            --set image.tag=${IMAGE_TAG} \
            --atomic --wait --timeout 5m
